version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    entrypoint: /bin/sh -c "ollama serve & sleep 30 && ollama pull ${OLLAMA_MODEL} && ollama run ${OLLAMA_MODEL}"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    container_name: ollama_nginx
    ports:
      - "${OLLAMA_PORT}:5577"
    env_file:
      - .env
    environment:
      - OLLAMA_USERNAME=${OLLAMA_USERNAME}
      - OLLAMA_PASSWORD=${OLLAMA_PASSWORD}
      - OLLAMA_PORT=${OLLAMA_PORT}
    depends_on:
      - ollama
    restart: unless-stopped
    command: /bin/sh -c "/usr/local/bin/htpasswd.sh && nginx -g 'daemon off;'"

volumes:
  ollama_data: