version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama serve & sleep 10 && ollama pull gemma2:9b-instruct-q5_K_M && ollama run gemma2:9b-instruct-q5_K_M"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ollama_nginx
    ports:
      - "${GEMMA2_PORT}:11434"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd.sh:/docker-entrypoint.d/htpasswd.sh
    env_file:
      - .env
    environment:
      - GEMMA2_USERNAME=${GEMMA2_USERNAME}
      - GEMMA2_PASSWORD=${GEMMA2_PASSWORD}
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: